#!/bin/sh

case "$1" in
    install)
        cat <<BANNER
----------------------------------------------------------------------

The substitutions filter dynamic module for nginx has been installed.
To enable this module, add the following to /etc/nginx/nginx.conf
and reload nginx:

    load_module modules/ngx_http_subs_filter_module.so;

Please refer to the module documentation for further details:
https://github.com/yaoweibin/ngx_http_substitutions_filter_module

----------------------------------------------------------------------
BANNER
        ;;
    upgrade|abort-upgrade)
        ;;
    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 0
        ;;
esac

#DEBHELPER#

exit 0
