#!/bin/sh

case "$1" in
    install)
        cat <<BANNER
----------------------------------------------------------------------

The Length Hiding Filter dynamic module for nginx has been installed.
To enable this module, add the following to /etc/nginx/nginx.conf
and reload nginx:

    load_module modules/ngx_http_length_hiding_filter_module.so;

Please refer to the module documentation for further details:
https://github.com/nulab/nginx-length-hiding-filter-module

----------------------------------------------------------------------
BANNER
        ;;
    upgrade|abort-upgrade)
        ;;
    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 0
        ;;
esac

#DEBHELPER#

exit 0
