objs/ngx_ssl_ct_module.so usr/lib/nginx/modules
objs/ngx_ssl_ct_module-debug.so usr/lib/nginx/modules
objs/ngx_http_ssl_ct_module.so usr/lib/nginx/modules
objs/ngx_http_ssl_ct_module-debug.so usr/lib/nginx/modules
objs/ngx_mail_ssl_ct_module.so usr/lib/nginx/modules
objs/ngx_mail_ssl_ct_module-debug.so usr/lib/nginx/modules
objs/ngx_stream_ssl_ct_module.so usr/lib/nginx/modules
objs/ngx_stream_ssl_ct_module-debug.so usr/lib/nginx/modules



