#!/usr/bin/perl -w

use Config;

my $vendorarch = substr($Config{vendorarch}, 1);

print <<EOT;
objs/ngx_http_perl_module.so usr/lib/nginx/modules
objs/ngx_http_perl_module-debug.so usr/lib/nginx/modules
EOT

print "objs/src/http/modules/perl/blib/arch/auto/nginx/nginx.so    $vendorarch/auto/nginx\n";
print "objs/src/http/modules/perl/blib/arch/auto/nginx/nginx-debug.so    $vendorarch/auto/nginx\n";
print "objs/src/http/modules/perl/blib/lib/nginx.pm    $vendorarch\n";
