#!/bin/sh

case "$1" in
    install)
        cat <<BANNER
----------------------------------------------------------------------

Stream server traffic status core dynamic module for nginx has been installed.
To enable this module, add the following to /etc/nginx/nginx.conf
and reload nginx:

    load_module modules/ngx_stream_server_traffic_status_module.so;

Please refer to the module documentation for further details:
https://github.com/vozlt/nginx-module-stream-sts

----------------------------------------------------------------------
BANNER
        ;;
    upgrade|abort-upgrade)
        ;;
    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 0
        ;;
esac

#DEBHELPER#

exit 0
